import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;

public class Main {
    public static void main(String[] args) throws IOException {
//        UravBalance.prepareUrBal();
//        UravBalance.createUrBal();
//        KPR.parseAndCreateKPR();
//        CorrectUV.createCorrectUvOG("Кор_Ш_Сев_ПО58","Шунт_Север", "Север_ПомимоКПР_Выведен", "Север_ПомимоКПР_Введен","100");
//        CorrectUV.createCorrectUvOnRE("Кор_Ш_Фрол+Б3+Б4_ПО47"
//                ,"Шунт_Фроловское+Бл-3+Бл-4"
//                , "Фрол-е+Б3+Б4_ПомимоКПР_Вывед"
//                , "Фрол-е+Б3+Б4_ПомимоКПР_Введен"
//                ,"500");
//        CorrectUV.createCorrectUvOnKE("Кор_Ш_Фрол+Б3+Б4_ПО47"
//                ,"Шунт_Фроловское+Бл-3+Бл-4"
//                , "Фрол-е+Б3+Б4_ПомимоКПР_Вывед"
//                , "Фрол-е+Б3+Б4_ПомимоКПР_Введен"
//                ,"500");
//        CorrectUV.createCorrectUvOnBH("Кор_Ш_Фрол+Б3+Б4_ПО47"
//                ,"Шунт_Фроловское+Бл-3+Бл-4"
//                , "Фрол-е+Б3+Б4_ПомимоКПР_Вывед"
//                , "Фрол-е+Б3+Б4_ПомимоКПР_Введен"
//                ,"500");
//        CorrectUV.createCorrectUvOnKP("Кор_Ш_Фрол+Б3+Б4_ПО47"
//                ,"Шунт_Фроловское+Бл-3+Бл-4"
//                , "Фрол-е+Б3+Б4_ПомимоКПР_Вывед"
//                , "Фрол-е+Б3+Б4_ПомимоКПР_Введен"
//                ,"500");
//        Map<String, String> schemesVolRost = new HashMap<>(ParseExcellScheme.parseExcel("data/VolRost.xlsx"));
//        CreateExcelScheme.scheme(schemesVolRost);
//        Map<String, String> schemesVolRostBl1 = new HashMap<>(ParseExcellScheme.parseExcel("data/VolRost_BL1.xlsx"));
//        CreateExcelScheme.scheme(schemesVolRostBl1);
//        Map<String, String> schemesVolRostBl2 = new HashMap<>(ParseExcellScheme.parseExcel("data/VolRost_BL2.xlsx"));
//        CreateExcelScheme.scheme(schemesVolRostBl2);
//        Map<String, String> schemesVolRostBl3 = new HashMap<>(ParseExcellScheme.parseExcel("data/VolRost_BL3.xlsx"));
//        CreateExcelScheme.scheme(schemesVolRostBl3);
//        Map<String, String> schemesVolRostBl4 = new HashMap<>(ParseExcellScheme.parseExcel("data/VolRost_BL4.xlsx"));
//        CreateExcelScheme.scheme(schemesVolRostBl4);
//        Map<String, String> schemesRostVol = new HashMap<>(ParseExcellScheme.parseExcel("data/RostVol.xlsx"));
//        CreateExcelScheme.scheme(schemesRostVol);
//        Map<String, String> schemesRostVolPSH = new HashMap<>(ParseExcellScheme.parseExcel("data/RostVol_PSH.xlsx"));
//        CreateExcelScheme.scheme(schemesRostVolPSH);
//        Map<String, String> volBl1 = new HashMap<>(ParseExcellScheme.parseExcel("data/Vol_BL1.xlsx"));
//        CreateExcelScheme.scheme(volBl1);
//        Map<String, String> volBl2 = new HashMap<>(ParseExcellScheme.parseExcel("data/Vol_BL2.xlsx"));
//        CreateExcelScheme.scheme(volBl2);
//        Map<String, String> volBl3 = new HashMap<>(ParseExcellScheme.parseExcel("data/Vol_BL3.xlsx"));
//        CreateExcelScheme.scheme(volBl3);
//        Map<String, String> volBl4 = new HashMap<>(ParseExcellScheme.parseExcel("data/Vol_BL4.xlsx"));
//        CreateExcelScheme.scheme(volBl4);
//        Map<String, String> frolBl1 = new HashMap<>(ParseExcellScheme.parseExcel("data/Frol_BL1.xlsx"));
//        CreateExcelScheme.scheme(frolBl1);
//        Map<String, String> frolBl2 = new HashMap<>(ParseExcellScheme.parseExcel("data/Frol_BL2.xlsx"));
//        CreateExcelScheme.scheme(frolBl2);
//        Map<String, String> frolBl3 = new HashMap<>(ParseExcellScheme.parseExcel("data/Frol_BL3.xlsx"));
//        CreateExcelScheme.scheme(frolBl3);
//        Map<String, String> frolBl4 = new HashMap<>(ParseExcellScheme.parseExcel("data/Frol_BL4.xlsx"));
//        CreateExcelScheme.scheme(frolBl4);
//        Map<String, String> volPSH = new HashMap<>(ParseExcellScheme.parseExcel("data/Vol_PSH.xlsx"));
//        CreateExcelScheme.scheme(volPSH);
//        Map<String, String> frolPSH = new HashMap<>(ParseExcellScheme.parseExcel("data/Frol_PSH.xlsx"));
//        CreateExcelScheme.scheme(frolPSH);
//        Map<String, String> sev = new HashMap<>(ParseExcellScheme.parseExcel("data/Sever.xlsx"));
//        CreateExcelScheme.scheme(sev);
//        Map<String, String> shachti = new HashMap<>(ParseExcellScheme.parseExcel("data/Shachti.xlsx"));
//        CreateExcelScheme.scheme(shachti);
//        Map<String, String> volRostBL12 = new HashMap<>(ParseExcellScheme.parseExcel("data/VolRost_BL1_BL2.xlsx"));
//        CreateExcelScheme.scheme(volRostBL12);
//        Map<String, String> volRostBL13 = new HashMap<>(ParseExcellScheme.parseExcel("data/VolRost_BL1_BL3.xlsx"));
//        CreateExcelScheme.scheme(volRostBL13);
//        Map<String, String> volRostBL23 = new HashMap<>(ParseExcellScheme.parseExcel("data/VolRost_BL2_BL3.xlsx"));
//        CreateExcelScheme.scheme(volRostBL23);
//        Map<String, String> volRostBL14 = new HashMap<>(ParseExcellScheme.parseExcel("data/VolRost_BL1_BL4.xlsx"));
//        CreateExcelScheme.scheme(volRostBL14);
//        Map<String, String> volRostBL24 = new HashMap<>(ParseExcellScheme.parseExcel("data/VolRost_BL2_BL4.xlsx"));
//        CreateExcelScheme.scheme(volRostBL24);
//        Map<String, String> volRostBL34 = new HashMap<>(ParseExcellScheme.parseExcel("data/VolRost_BL3_BL4.xlsx"));
//        CreateExcelScheme.scheme(volRostBL34);
//        Map<String, String> volBL12 = new HashMap<>(ParseExcellScheme.parseExcel("data/Vol_BL1_BL2.xlsx"));
//        CreateExcelScheme.scheme(volBL12);
//        Map<String, String> volBL13 = new HashMap<>(ParseExcellScheme.parseExcel("data/Vol_BL1_BL3.xlsx"));
//        CreateExcelScheme.scheme(volBL13);
//        Map<String, String> volBL23 = new HashMap<>(ParseExcellScheme.parseExcel("data/Vol_BL2_BL3.xlsx"));
//        CreateExcelScheme.scheme(volBL23);
//        Map<String, String> volBL14 = new HashMap<>(ParseExcellScheme.parseExcel("data/Vol_BL1_BL4.xlsx"));
//        CreateExcelScheme.scheme(volBL14);
//        Map<String, String> volBL24 = new HashMap<>(ParseExcellScheme.parseExcel("data/Vol_BL2_BL4.xlsx"));
//        CreateExcelScheme.scheme(volBL24);
//        Map<String, String> volBL34 = new HashMap<>(ParseExcellScheme.parseExcel("data/Vol_BL3_BL4.xlsx"));
//        CreateExcelScheme.scheme(volBL34);
//        Map<String, String> frolBL12 = new HashMap<>(ParseExcellScheme.parseExcel("data/Frol_BL1_BL2.xlsx"));
//        CreateExcelScheme.scheme(frolBL12);
//        Map<String, String> frolBL13 = new HashMap<>(ParseExcellScheme.parseExcel("data/Frol_BL1_BL3.xlsx"));
//        CreateExcelScheme.scheme(frolBL13);
//        Map<String, String> frolBL23 = new HashMap<>(ParseExcellScheme.parseExcel("data/Frol_BL2_BL3.xlsx"));
//        CreateExcelScheme.scheme(frolBL23);
//        Map<String, String> frolBL14 = new HashMap<>(ParseExcellScheme.parseExcel("data/Frol_BL1_BL4.xlsx"));
//        CreateExcelScheme.scheme(frolBL14);
//        Map<String, String> frolBL24 = new HashMap<>(ParseExcellScheme.parseExcel("data/Frol_BL2_BL4.xlsx"));
//        CreateExcelScheme.scheme(frolBL24);
//        Map<String, String> frolBL34 = new HashMap<>(ParseExcellScheme.parseExcel("data/Frol_BL3_BL4.xlsx"));
//        CreateExcelScheme.scheme(frolBL34);
//        CreateExcelScheme.closeScheme();
//        ArrayList<String> tableUvVR = new ArrayList<>(ParseExcelTable.parseExcelTable("data/VolRost.xlsx"));
//        CreateExcelTable.table(tableUvVR);
//        HashSet<String> volRost1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost.xlsx", 0));
//        HashSet<String> volRost2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost.xlsx", 1));
//        HashSet<String> volRost3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost.xlsx", 2));
//        HashSet<String> volRost4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost.xlsx", 3));
//        HashSet<String> volRost5 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost.xlsx", 4));
//        HashSet<String> volRost6 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost.xlsx", 5));
//        HashSet<String> volRost7 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost.xlsx", 6));
//        ArrayList<String> listFpoVr =new ArrayList<>();
//        listFpoVr.addAll(ParseExcelTableFpo.createTableFpoString(volRost2,volRost1,"{ВР}","КПР1_Волгоград-Ростов","[Текущий_сезон=ЛЕТО]"));
//        listFpoVr.addAll(ParseExcelTableFpo.createTableFpoString(volRost3,volRost1,"{ВР}","КПР1_Волгоград-Ростов","[Текущий_сезон=ЛЕТО]"));
//        listFpoVr.addAll(ParseExcelTableFpo.createTableFpoString(volRost4,volRost1,"{ВР}","КПР1_Волгоград-Ростов","[Текущий_сезон=ЛЕТО]"));
//        listFpoVr.addAll(ParseExcelTableFpo.createTableFpoString(volRost1,volRost2,"{ВР}","КПР2_Волгоград-Ростов","[Текущий_сезон=ЛЕТО]"));
//        listFpoVr.addAll(ParseExcelTableFpo.createTableFpoString(volRost3,volRost2,"{ВР}","КПР2_Волгоград-Ростов","[Текущий_сезон=ЛЕТО]"));
//        listFpoVr.addAll(ParseExcelTableFpo.createTableFpoString(volRost4,volRost2,"{ВР}","КПР2_Волгоград-Ростов","[Текущий_сезон=ЛЕТО]"));
//        listFpoVr.addAll(ParseExcelTableFpo.createTableFpoString(volRost1,volRost3,"{ВР}","КПР3_Волгоград-Ростов","[Текущий_сезон=ЛЕТО]"));
//        listFpoVr.addAll(ParseExcelTableFpo.createTableFpoString(volRost2,volRost3,"{ВР}","КПР3_Волгоград-Ростов","[Текущий_сезон=ЛЕТО]"));
//        listFpoVr.addAll(ParseExcelTableFpo.createTableFpoString(volRost4,volRost3,"{ВР}","КПР3_Волгоград-Ростов","[Текущий_сезон=ЛЕТО]"));
//        listFpoVr.addAll(ParseExcelTableFpo.createTableFpoString(volRost1,volRost4,"{ВР}","КПР4_Волгоград-Ростов","[Текущий_сезон=ЛЕТО]"));
//        listFpoVr.addAll(ParseExcelTableFpo.createTableFpoString(volRost2,volRost4,"{ВР}","КПР4_Волгоград-Ростов","[Текущий_сезон=ЛЕТО]"));
//        listFpoVr.addAll(ParseExcelTableFpo.createTableFpoString(volRost3,volRost4,"{ВР}","КПР4_Волгоград-Ростов","[Текущий_сезон=ЛЕТО]"));
//        listFpoVr.addAll(ParseExcelTableFpo.createTableFpoString(volRost6,volRost5,"{ВР}","КПР1_Волгоград-Ростов","[Текущий_сезон=ЗИМА]"));
//        listFpoVr.addAll(ParseExcelTableFpo.createTableFpoString(volRost7,volRost5,"{ВР}","КПР1_Волгоград-Ростов","[Текущий_сезон=ЗИМА]"));
//        listFpoVr.addAll(ParseExcelTableFpo.createTableFpoString(volRost5,volRost6,"{ВР}","КПР3_Волгоград-Ростов","[Текущий_сезон=ЗИМА]"));
//        listFpoVr.addAll(ParseExcelTableFpo.createTableFpoString(volRost7,volRost6,"{ВР}","КПР3_Волгоград-Ростов","[Текущий_сезон=ЗИМА]"));
//        listFpoVr.addAll(ParseExcelTableFpo.createTableFpoString(volRost5,volRost7,"{ВР}","КПР4_Волгоград-Ростов","[Текущий_сезон=ЗИМА]"));
//        listFpoVr.addAll(ParseExcelTableFpo.createTableFpoString(volRost6,volRost7,"{ВР}","КПР4_Волгоград-Ростов","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoVr);
//        ArrayList<String> tableUvVRBL1 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/VolRost_BL1.xlsx"));
//        CreateExcelTable.table(tableUvVRBL1);
//        HashSet<String> volRost1Bl1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1.xlsx", 0));
//        HashSet<String> volRost1Bl2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1.xlsx", 1));
//        HashSet<String> volRost1Bl3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1.xlsx", 2));
//        HashSet<String> volRost1Bl4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1.xlsx", 3));
//        HashSet<String> volRost1Bl5 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1.xlsx", 4));
//        HashSet<String> volRost1Bl6 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1.xlsx", 5));
//        ArrayList<String> listFpoVrBL1 =new ArrayList<>();
//        listFpoVrBL1.addAll(ParseExcelTableFpo.createTableFpoString(volRost1Bl2,volRost1Bl1,"{ВР_БЛ1}","КПР1_Волгоград-Ростов+Бл-1","[Текущий_сезон=ЛЕТО]"));
//        listFpoVrBL1.addAll(ParseExcelTableFpo.createTableFpoString(volRost1Bl3,volRost1Bl1,"{ВР_БЛ1}","КПР1_Волгоград-Ростов+Бл-1","[Текущий_сезон=ЛЕТО]"));
//        listFpoVrBL1.addAll(ParseExcelTableFpo.createTableFpoString(volRost1Bl1,volRost1Bl2,"{ВР_БЛ1}","КПР3_Волгоград-Ростов+Бл-1","[Текущий_сезон=ЛЕТО]"));
//        listFpoVrBL1.addAll(ParseExcelTableFpo.createTableFpoString(volRost1Bl3,volRost1Bl2,"{ВР_БЛ1}","КПР3_Волгоград-Ростов+Бл-1","[Текущий_сезон=ЛЕТО]"));
//        listFpoVrBL1.addAll(ParseExcelTableFpo.createTableFpoString(volRost1Bl1,volRost1Bl3,"{ВР_БЛ1}","КПР2_Волгоград-Ростов+Бл-1","[Текущий_сезон=ЛЕТО]"));
//        listFpoVrBL1.addAll(ParseExcelTableFpo.createTableFpoString(volRost1Bl2,volRost1Bl3,"{ВР_БЛ1}","КПР2_Волгоград-Ростов+Бл-1","[Текущий_сезон=ЛЕТО]"));
//        listFpoVrBL1.addAll(ParseExcelTableFpo.createTableFpoString(volRost1Bl5,volRost1Bl4,"{ВР_БЛ1}","КПР2_Волгоград-Ростов+Бл-1","[Текущий_сезон=ЗИМА]"));
//        listFpoVrBL1.addAll(ParseExcelTableFpo.createTableFpoString(volRost1Bl6,volRost1Bl4,"{ВР_БЛ1}","КПР2_Волгоград-Ростов+Бл-1","[Текущий_сезон=ЗИМА]"));
//        listFpoVrBL1.addAll(ParseExcelTableFpo.createTableFpoString(volRost1Bl4,volRost1Bl5,"{ВР_БЛ1}","КПР1_Волгоград-Ростов+Бл-1","[Текущий_сезон=ЗИМА]"));
//        listFpoVrBL1.addAll(ParseExcelTableFpo.createTableFpoString(volRost1Bl6,volRost1Bl5,"{ВР_БЛ1}","КПР1_Волгоград-Ростов+Бл-1","[Текущий_сезон=ЗИМА]"));
//        listFpoVrBL1.addAll(ParseExcelTableFpo.createTableFpoString(volRost1Bl4,volRost1Bl6,"{ВР_БЛ1}","КПР3_Волгоград-Ростов+Бл-1","[Текущий_сезон=ЗИМА]"));
//        listFpoVrBL1.addAll(ParseExcelTableFpo.createTableFpoString(volRost1Bl5,volRost1Bl6,"{ВР_БЛ1}","КПР3_Волгоград-Ростов+Бл-1","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoVrBL1);
//        ArrayList<String> tableUvVRBL2 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/VolRost_BL2.xlsx"));
//        CreateExcelTable.table(tableUvVRBL2);
//        HashSet<String> volRost2Bl1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL2.xlsx", 0));
//        HashSet<String> volRost2Bl2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL2.xlsx", 1));
//        HashSet<String> volRost2Bl3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL2.xlsx", 2));
//        HashSet<String> volRost2Bl4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL2.xlsx", 3));
//        HashSet<String> volRost2Bl5 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL2.xlsx", 4));
//        HashSet<String> volRost2Bl6 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL2.xlsx", 5));
//        ArrayList<String> listFpoVrBL2 =new ArrayList<>();
//        listFpoVrBL2.addAll(ParseExcelTableFpo.createTableFpoString(volRost2Bl2,volRost2Bl1,"{ВР_БЛ2}","КПР1_Волгоград-Ростов+Бл-2","[Текущий_сезон=ЛЕТО]"));
//        listFpoVrBL2.addAll(ParseExcelTableFpo.createTableFpoString(volRost2Bl3,volRost2Bl1,"{ВР_БЛ2}","КПР1_Волгоград-Ростов+Бл-2","[Текущий_сезон=ЛЕТО]"));
//        listFpoVrBL2.addAll(ParseExcelTableFpo.createTableFpoString(volRost2Bl1,volRost2Bl2,"{ВР_БЛ2}","КПР3_Волгоград-Ростов+Бл-2","[Текущий_сезон=ЛЕТО]"));
//        listFpoVrBL2.addAll(ParseExcelTableFpo.createTableFpoString(volRost2Bl3,volRost2Bl2,"{ВР_БЛ2}","КПР3_Волгоград-Ростов+Бл-2","[Текущий_сезон=ЛЕТО]"));
//        listFpoVrBL2.addAll(ParseExcelTableFpo.createTableFpoString(volRost2Bl1,volRost2Bl3,"{ВР_БЛ2}","КПР2_Волгоград-Ростов+Бл-2","[Текущий_сезон=ЛЕТО]"));
//        listFpoVrBL2.addAll(ParseExcelTableFpo.createTableFpoString(volRost2Bl2,volRost2Bl3,"{ВР_БЛ2}","КПР2_Волгоград-Ростов+Бл-2","[Текущий_сезон=ЛЕТО]"));
//        listFpoVrBL2.addAll(ParseExcelTableFpo.createTableFpoString(volRost2Bl5,volRost2Bl4,"{ВР_БЛ2}","КПР2_Волгоград-Ростов+Бл-2","[Текущий_сезон=ЗИМА]"));
//        listFpoVrBL2.addAll(ParseExcelTableFpo.createTableFpoString(volRost2Bl6,volRost2Bl4,"{ВР_БЛ2}","КПР2_Волгоград-Ростов+Бл-2","[Текущий_сезон=ЗИМА]"));
//        listFpoVrBL2.addAll(ParseExcelTableFpo.createTableFpoString(volRost2Bl4,volRost2Bl5,"{ВР_БЛ2}","КПР1_Волгоград-Ростов+Бл-2","[Текущий_сезон=ЗИМА]"));
//        listFpoVrBL2.addAll(ParseExcelTableFpo.createTableFpoString(volRost2Bl6,volRost2Bl5,"{ВР_БЛ2}","КПР1_Волгоград-Ростов+Бл-2","[Текущий_сезон=ЗИМА]"));
//        listFpoVrBL2.addAll(ParseExcelTableFpo.createTableFpoString(volRost2Bl4,volRost2Bl6,"{ВР_БЛ2}","КПР3_Волгоград-Ростов+Бл-2","[Текущий_сезон=ЗИМА]"));
//        listFpoVrBL2.addAll(ParseExcelTableFpo.createTableFpoString(volRost2Bl5,volRost2Bl6,"{ВР_БЛ2}","КПР3_Волгоград-Ростов+Бл-2","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoVrBL2);
//        ArrayList<String> tableUvVRBL3 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/VolRost_BL3.xlsx"));
//        CreateExcelTable.table(tableUvVRBL3);
//        HashSet<String> volRost3Bl1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL3.xlsx", 0));
//        HashSet<String> volRost3Bl2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL3.xlsx", 1));
//        HashSet<String> volRost3Bl3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL3.xlsx", 2));
//        HashSet<String> volRost3Bl4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL3.xlsx", 3));
//        HashSet<String> volRost3Bl5 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL3.xlsx", 4));
//        HashSet<String> volRost3Bl6 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL3.xlsx", 5));
//        ArrayList<String> listFpoVrBL3 =new ArrayList<>();
//        listFpoVrBL3.addAll(ParseExcelTableFpo.createTableFpoString(volRost3Bl2,volRost3Bl1,"{ВР_БЛ3}","КПР1_Волгоград-Ростов+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoVrBL3.addAll(ParseExcelTableFpo.createTableFpoString(volRost3Bl3,volRost3Bl1,"{ВР_БЛ3}","КПР1_Волгоград-Ростов+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoVrBL3.addAll(ParseExcelTableFpo.createTableFpoString(volRost3Bl1,volRost3Bl2,"{ВР_БЛ3}","КПР3_Волгоград-Ростов+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoVrBL3.addAll(ParseExcelTableFpo.createTableFpoString(volRost3Bl3,volRost3Bl2,"{ВР_БЛ3}","КПР3_Волгоград-Ростов+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoVrBL3.addAll(ParseExcelTableFpo.createTableFpoString(volRost3Bl1,volRost3Bl3,"{ВР_БЛ3}","КПР2_Волгоград-Ростов+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoVrBL3.addAll(ParseExcelTableFpo.createTableFpoString(volRost3Bl2,volRost3Bl3,"{ВР_БЛ3}","КПР2_Волгоград-Ростов+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoVrBL3.addAll(ParseExcelTableFpo.createTableFpoString(volRost3Bl5,volRost3Bl4,"{ВР_БЛ3}","КПР2_Волгоград-Ростов+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVrBL3.addAll(ParseExcelTableFpo.createTableFpoString(volRost3Bl6,volRost3Bl4,"{ВР_БЛ3}","КПР2_Волгоград-Ростов+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVrBL3.addAll(ParseExcelTableFpo.createTableFpoString(volRost3Bl4,volRost3Bl5,"{ВР_БЛ3}","КПР1_Волгоград-Ростов+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVrBL3.addAll(ParseExcelTableFpo.createTableFpoString(volRost3Bl6,volRost3Bl5,"{ВР_БЛ3}","КПР1_Волгоград-Ростов+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVrBL3.addAll(ParseExcelTableFpo.createTableFpoString(volRost3Bl4,volRost3Bl6,"{ВР_БЛ3}","КПР3_Волгоград-Ростов+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVrBL3.addAll(ParseExcelTableFpo.createTableFpoString(volRost3Bl5,volRost3Bl6,"{ВР_БЛ3}","КПР3_Волгоград-Ростов+Бл-3","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoVrBL3);
//        ArrayList<String> tableUvVRBL4 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/VolRost_BL4.xlsx"));
//        CreateExcelTable.table(tableUvVRBL4);
//        HashSet<String> volRost4Bl1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL4.xlsx", 0));
//        HashSet<String> volRost4Bl2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL4.xlsx", 1));
//        HashSet<String> volRost4Bl3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL4.xlsx", 2));
//        HashSet<String> volRost4Bl4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL4.xlsx", 3));
//        HashSet<String> volRost4Bl5 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL4.xlsx", 4));
//        HashSet<String> volRost4Bl6 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL4.xlsx", 5));
//        ArrayList<String> listFpoVrBL4 =new ArrayList<>();
//        listFpoVrBL4.addAll(ParseExcelTableFpo.createTableFpoString(volRost4Bl2,volRost4Bl1,"{ВР_БЛ4}","КПР1_Волгоград-Ростов+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVrBL4.addAll(ParseExcelTableFpo.createTableFpoString(volRost4Bl3,volRost4Bl1,"{ВР_БЛ4}","КПР1_Волгоград-Ростов+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVrBL4.addAll(ParseExcelTableFpo.createTableFpoString(volRost4Bl1,volRost4Bl2,"{ВР_БЛ4}","КПР3_Волгоград-Ростов+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVrBL4.addAll(ParseExcelTableFpo.createTableFpoString(volRost4Bl3,volRost4Bl2,"{ВР_БЛ4}","КПР3_Волгоград-Ростов+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVrBL4.addAll(ParseExcelTableFpo.createTableFpoString(volRost4Bl1,volRost4Bl3,"{ВР_БЛ4}","КПР2_Волгоград-Ростов+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVrBL4.addAll(ParseExcelTableFpo.createTableFpoString(volRost4Bl2,volRost4Bl3,"{ВР_БЛ4}","КПР2_Волгоград-Ростов+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVrBL4.addAll(ParseExcelTableFpo.createTableFpoString(volRost4Bl5,volRost4Bl4,"{ВР_БЛ4}","КПР2_Волгоград-Ростов+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVrBL4.addAll(ParseExcelTableFpo.createTableFpoString(volRost4Bl6,volRost4Bl4,"{ВР_БЛ4}","КПР2_Волгоград-Ростов+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVrBL4.addAll(ParseExcelTableFpo.createTableFpoString(volRost4Bl4,volRost4Bl5,"{ВР_БЛ4}","КПР1_Волгоград-Ростов+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVrBL4.addAll(ParseExcelTableFpo.createTableFpoString(volRost4Bl6,volRost4Bl5,"{ВР_БЛ4}","КПР1_Волгоград-Ростов+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVrBL4.addAll(ParseExcelTableFpo.createTableFpoString(volRost4Bl4,volRost4Bl6,"{ВР_БЛ4}","КПР3_Волгоград-Ростов+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVrBL4.addAll(ParseExcelTableFpo.createTableFpoString(volRost4Bl5,volRost4Bl6,"{ВР_БЛ4}","КПР3_Волгоград-Ростов+Бл-4","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoVrBL4);
//        ArrayList<String> tableUvRV = new ArrayList<>(ParseExcelTable.parseExcelTable("data/RostVol.xlsx"));
//        CreateExcelTable.table(tableUvRV);
//        HashSet<String> rostVol1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/RostVol.xlsx", 0));
//        HashSet<String> rostVol2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/RostVol.xlsx", 1));
//        HashSet<String> rostVol3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/RostVol.xlsx", 2));
//        HashSet<String> rostVol4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/RostVol.xlsx", 3));
//        ArrayList<String> listFpoRv =new ArrayList<>();
//        listFpoRv.addAll(ParseExcelTableFpo.createTableFpoString(rostVol2,rostVol1,"{РВ}","КПР-1_Ростов-Волгоград","[Текущий_сезон=ЛЕТО]"));
//        listFpoRv.addAll(ParseExcelTableFpo.createTableFpoString(rostVol1,rostVol2,"{РВ}","КПР-2_Ростов-Волгоград","[Текущий_сезон=ЛЕТО]"));
//        listFpoRv.addAll(ParseExcelTableFpo.createTableFpoString(rostVol4,rostVol3,"{РВ}","КПР-1_Ростов-Волгоград","[Текущий_сезон=ЗИМА]"));
//        listFpoRv.addAll(ParseExcelTableFpo.createTableFpoString(rostVol3,rostVol4,"{РВ}","КПР-2_Ростов-Волгоград","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoRv);
//        ArrayList<String> tableUvRvPSH = new ArrayList<>(ParseExcelTable.parseExcelTable("data/RostVol_PSH.xlsx"));
//        CreateExcelTable.table(tableUvRvPSH);
//        HashSet<String> rostVolPSH1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/RostVol_PSH.xlsx", 0));
//        HashSet<String> rostVolPSH2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/RostVol_PSH.xlsx", 1));
//        HashSet<String> rostVolPSH3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/RostVol_PSH.xlsx", 2));
//        HashSet<String> rostVolPSH4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/RostVol_PSH.xlsx", 3));
//        ArrayList<String> listFpoRvPSH =new ArrayList<>();
//        listFpoRvPSH.addAll(ParseExcelTableFpo.createTableFpoString(rostVolPSH2,rostVolPSH1,"{РВ_ПШ}","КПР-1_Ростов-Волгоград+ПШ","[Текущий_сезон=ЛЕТО]"));
//        listFpoRvPSH.addAll(ParseExcelTableFpo.createTableFpoString(rostVolPSH1,rostVolPSH2,"{РВ_ПШ}","КПР-2_Ростов-Волгоград+ПШ","[Текущий_сезон=ЛЕТО]"));
//        listFpoRvPSH.addAll(ParseExcelTableFpo.createTableFpoString(rostVolPSH4,rostVolPSH3,"{РВ_ПШ}","КПР-1_Ростов-Волгоград+ПШ","[Текущий_сезон=ЗИМА]"));
//        listFpoRvPSH.addAll(ParseExcelTableFpo.createTableFpoString(rostVolPSH3,rostVolPSH4,"{РВ_ПШ}","КПР-2_Ростов-Волгоград+ПШ","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoRvPSH);
//        ArrayList<String> tableVolBL1 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/Vol_BL1.xlsx"));
//        CreateExcelTable.table(tableVolBL1);
//        HashSet<String> vol1BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL1.xlsx", 0));
//        HashSet<String> vol1BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL1.xlsx", 1));
//        HashSet<String> vol1BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL1.xlsx", 2));
//        HashSet<String> vol1BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL1.xlsx", 3));
//        ArrayList<String> listFpoVBL1 =new ArrayList<>();
//        listFpoVBL1.addAll(ParseExcelTableFpo.createTableFpoString(vol1BL2,vol1BL1,"{В_БЛ1}","КПР1_Волгоградское+Бл-1","[Текущий_сезон=ЛЕТО]"));
//        listFpoVBL1.addAll(ParseExcelTableFpo.createTableFpoString(vol1BL1,vol1BL2,"{В_БЛ1}","КПР2_Волгоградское+Бл-1","[Текущий_сезон=ЛЕТО]"));
//        listFpoVBL1.addAll(ParseExcelTableFpo.createTableFpoString(vol1BL4,vol1BL3,"{В_БЛ1}","КПР1_Волгоградское+Бл-1","[Текущий_сезон=ЗИМА]"));
//        listFpoVBL1.addAll(ParseExcelTableFpo.createTableFpoString(vol1BL3,vol1BL4,"{В_БЛ1}","КПР2_Волгоградское+Бл-1","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoVBL1);
//        ArrayList<String> tableVolBL2 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/Vol_BL2.xlsx"));
//        CreateExcelTable.table(tableVolBL2);
//        HashSet<String> vol2BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL2.xlsx", 0));
//        HashSet<String> vol2BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL2.xlsx", 1));
//        HashSet<String> vol2BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL2.xlsx", 2));
//        HashSet<String> vol2BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL2.xlsx", 3));
//        ArrayList<String> listFpoVBL2 =new ArrayList<>();
//        listFpoVBL2.addAll(ParseExcelTableFpo.createTableFpoString(vol2BL2,vol2BL1,"{В_БЛ2}","КПР1_Волгоградское+Бл-2","[Текущий_сезон=ЛЕТО]"));
//        listFpoVBL2.addAll(ParseExcelTableFpo.createTableFpoString(vol2BL1,vol2BL2,"{В_БЛ2}","КПР2_Волгоградское+Бл-2","[Текущий_сезон=ЛЕТО]"));
//        listFpoVBL2.addAll(ParseExcelTableFpo.createTableFpoString(vol2BL4,vol2BL3,"{В_БЛ2}","КПР1_Волгоградское+Бл-2","[Текущий_сезон=ЗИМА]"));
//        listFpoVBL2.addAll(ParseExcelTableFpo.createTableFpoString(vol2BL3,vol2BL4,"{В_БЛ2}","КПР2_Волгоградское+Бл-2","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoVBL2);
//        ArrayList<String> tableVolBL3 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/Vol_BL3.xlsx"));
//        CreateExcelTable.table(tableVolBL3);
//        HashSet<String> vol3BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL3.xlsx", 0));
//        HashSet<String> vol3BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL3.xlsx", 1));
//        HashSet<String> vol3BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL3.xlsx", 2));
//        HashSet<String> vol3BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL3.xlsx", 3));
//        ArrayList<String> listFpoVBL3 =new ArrayList<>();
//        listFpoVBL3.addAll(ParseExcelTableFpo.createTableFpoString(vol3BL2,vol3BL1,"{В_БЛ3}","КПР1_Волгоградское+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoVBL3.addAll(ParseExcelTableFpo.createTableFpoString(vol3BL1,vol3BL2,"{В_БЛ3}","КПР2_Волгоградское+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoVBL3.addAll(ParseExcelTableFpo.createTableFpoString(vol3BL4,vol3BL3,"{В_БЛ3}","КПР1_Волгоградское+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVBL3.addAll(ParseExcelTableFpo.createTableFpoString(vol3BL3,vol3BL4,"{В_БЛ3}","КПР2_Волгоградское+Бл-3","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoVBL3);
//        ArrayList<String> tableVolBL4 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/Vol_BL4.xlsx"));
//        CreateExcelTable.table(tableVolBL4);
//        HashSet<String> vol4BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL4.xlsx", 0));
//        HashSet<String> vol4BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL4.xlsx", 1));
//        HashSet<String> vol4BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL4.xlsx", 2));
//        HashSet<String> vol4BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL4.xlsx", 3));
//        ArrayList<String> listFpoVBL4 =new ArrayList<>();
//        listFpoVBL4.addAll(ParseExcelTableFpo.createTableFpoString(vol4BL2,vol4BL1,"{В_БЛ4}","КПР1_Волгоградское+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVBL4.addAll(ParseExcelTableFpo.createTableFpoString(vol4BL1,vol4BL2,"{В_БЛ4}","КПР2_Волгоградское+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVBL4.addAll(ParseExcelTableFpo.createTableFpoString(vol4BL4,vol4BL3,"{В_БЛ4}","КПР1_Волгоградское+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVBL4.addAll(ParseExcelTableFpo.createTableFpoString(vol4BL3,vol4BL4,"{В_БЛ4}","КПР2_Волгоградское+Бл-4","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoVBL4);
//        ArrayList<String> tableFrolBL1 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/Frol_BL1.xlsx"));
//        CreateExcelTable.table(tableFrolBL1);
//        HashSet<String> frol1BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL1.xlsx", 0));
//        HashSet<String> frol1BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL1.xlsx", 1));
//        HashSet<String> frol1BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL1.xlsx", 2));
//        HashSet<String> frol1BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL1.xlsx", 3));
//        ArrayList<String> listFpoFBL1 =new ArrayList<>();
//        listFpoFBL1.addAll(ParseExcelTableFpo.createTableFpoString(frol1BL2,frol1BL1,"{Ф_БЛ1}","КПР-1_Фроловское+Бл-1","[Текущий_сезон=ЛЕТО]"));
//        listFpoFBL1.addAll(ParseExcelTableFpo.createTableFpoString(frol1BL1,frol1BL2,"{Ф_БЛ1}","КПР-2_Фроловское+Бл-1","[Текущий_сезон=ЛЕТО]"));
//        listFpoFBL1.addAll(ParseExcelTableFpo.createTableFpoString(frol1BL4,frol1BL3,"{Ф_БЛ1}","КПР-1_Фроловское+Бл-1","[Текущий_сезон=ЗИМА]"));
//        listFpoFBL1.addAll(ParseExcelTableFpo.createTableFpoString(frol1BL3,frol1BL4,"{Ф_БЛ1}","КПР-2_Фроловское+Бл-1","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoFBL1);
//        ArrayList<String> tableFrolBL2 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/Frol_BL2.xlsx"));
//        CreateExcelTable.table(tableFrolBL2);
//        HashSet<String> frol2BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL2.xlsx", 0));
//        HashSet<String> frol2BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL2.xlsx", 1));
//        HashSet<String> frol2BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL2.xlsx", 2));
//        HashSet<String> frol2BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL2.xlsx", 3));
//        ArrayList<String> listFpoFBL2 =new ArrayList<>();
//        listFpoFBL2.addAll(ParseExcelTableFpo.createTableFpoString(frol2BL2,frol2BL1,"{Ф_БЛ2}","КПР-1_Фроловское+Бл-2","[Текущий_сезон=ЛЕТО]"));
//        listFpoFBL2.addAll(ParseExcelTableFpo.createTableFpoString(frol2BL1,frol2BL2,"{Ф_БЛ2}","КПР-2_Фроловское+Бл-2","[Текущий_сезон=ЛЕТО]"));
//        listFpoFBL2.addAll(ParseExcelTableFpo.createTableFpoString(frol2BL4,frol2BL3,"{Ф_БЛ2}","КПР-1_Фроловское+Бл-2","[Текущий_сезон=ЗИМА]"));
//        listFpoFBL2.addAll(ParseExcelTableFpo.createTableFpoString(frol2BL3,frol2BL4,"{Ф_БЛ2}","КПР-2_Фроловское+Бл-2","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoFBL2);
//        ArrayList<String> tableFrolBL3 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/Frol_BL3.xlsx"));
//        CreateExcelTable.table(tableFrolBL3);
//        HashSet<String> frol3BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL3.xlsx", 0));
//        HashSet<String> frol3BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL3.xlsx", 1));
//        HashSet<String> frol3BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL3.xlsx", 2));
//        HashSet<String> frol3BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL3.xlsx", 3));
//        ArrayList<String> listFpoFBL3 =new ArrayList<>();
//        listFpoFBL3.addAll(ParseExcelTableFpo.createTableFpoString(frol3BL2,frol3BL1,"{Ф_БЛ3}","КПР-1_Фроловское+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoFBL3.addAll(ParseExcelTableFpo.createTableFpoString(frol3BL1,frol3BL2,"{Ф_БЛ3}","КПР-2_Фроловское+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoFBL3.addAll(ParseExcelTableFpo.createTableFpoString(frol3BL4,frol3BL3,"{Ф_БЛ3}","КПР-1_Фроловское+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoFBL3.addAll(ParseExcelTableFpo.createTableFpoString(frol3BL3,frol3BL4,"{Ф_БЛ3}","КПР-2_Фроловское+Бл-3","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoFBL3);
//        ArrayList<String> tableFrolBL4 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/Frol_BL4.xlsx"));
//        CreateExcelTable.table(tableFrolBL4);
//        HashSet<String> frol4BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL4.xlsx", 0));
//        HashSet<String> frol4BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL4.xlsx", 1));
//        HashSet<String> frol4BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL4.xlsx", 2));
//        HashSet<String> frol4BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL4.xlsx", 3));
//        ArrayList<String> listFpoFBL4 =new ArrayList<>();
//        listFpoFBL4.addAll(ParseExcelTableFpo.createTableFpoString(frol4BL2,frol4BL1,"{Ф_БЛ4}","КПР-1_Фроловское+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoFBL4.addAll(ParseExcelTableFpo.createTableFpoString(frol4BL1,frol4BL2,"{Ф_БЛ4}","КПР-2_Фроловское+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoFBL4.addAll(ParseExcelTableFpo.createTableFpoString(frol4BL4,frol4BL3,"{Ф_БЛ4}","КПР-1_Фроловское+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoFBL4.addAll(ParseExcelTableFpo.createTableFpoString(frol4BL3,frol4BL4,"{Ф_БЛ4}","КПР-2_Фроловское+Бл-4","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoFBL4);
//        ArrayList<String> tableVolPSH = new ArrayList<>(ParseExcelTable.parseExcelTable("data/Vol_PSH.xlsx"));
//        CreateExcelTable.table(tableVolPSH);
//        HashSet<String> volPSH1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_PSH.xlsx", 0));
//        HashSet<String> volPSH2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_PSH.xlsx", 1));
//        HashSet<String> volPSH3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_PSH.xlsx", 2));
//        HashSet<String> volPSH4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_PSH.xlsx", 3));
//        ArrayList<String> listFpoVolPSH =new ArrayList<>();
//        listFpoVolPSH.addAll(ParseExcelTableFpo.createTableFpoString(volPSH2,volPSH1,"{В_ПШ}","КПР1_Волгоградское_из_ОЭС_Юга+ПШ","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolPSH.addAll(ParseExcelTableFpo.createTableFpoString(volPSH1,volPSH2,"{В_ПШ}","КПР2_Волгоградское_из_ОЭС_Юга+ПШ","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolPSH.addAll(ParseExcelTableFpo.createTableFpoString(volPSH4,volPSH3,"{В_ПШ}","КПР1_Волгоградское_из_ОЭС_Юга+ПШ","[Текущий_сезон=ЗИМА]"));
//        listFpoVolPSH.addAll(ParseExcelTableFpo.createTableFpoString(volPSH3,volPSH4,"{В_ПШ}","КПР2_Волгоградское_из_ОЭС_Юга+ПШ","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoVolPSH);
//        ArrayList<String> tableFrolPSH = new ArrayList<>(ParseExcelTable.parseExcelTable("data/Frol_PSH.xlsx"));
//        CreateExcelTable.table(tableFrolPSH);
//        HashSet<String> frolPSH1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_PSH.xlsx", 0));
//        HashSet<String> frolPSH2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_PSH.xlsx", 1));
//        HashSet<String> frolPSH3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_PSH.xlsx", 2));
//        HashSet<String> frolPSH4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_PSH.xlsx", 3));
//        ArrayList<String> listFpoFrolPSH =new ArrayList<>();
//        listFpoFrolPSH.addAll(ParseExcelTableFpo.createTableFpoString(frolPSH2,frolPSH1,"{Ф_ПШ}","КПР1_Фроловское_из_ОЭС_Юга+ПШ","[Текущий_сезон=ЛЕТО]"));
//        listFpoFrolPSH.addAll(ParseExcelTableFpo.createTableFpoString(frolPSH1,frolPSH2,"{Ф_ПШ}","КПР2_Фроловское_из_ОЭС_Юга+ПШ","[Текущий_сезон=ЛЕТО]"));
//        listFpoFrolPSH.addAll(ParseExcelTableFpo.createTableFpoString(frolPSH4,frolPSH3,"{Ф_ПШ}","КПР1_Фроловское_из_ОЭС_Юга+ПШ","[Текущий_сезон=ЗИМА]"));
//        listFpoFrolPSH.addAll(ParseExcelTableFpo.createTableFpoString(frolPSH3,frolPSH4,"{Ф_ПШ}","КПР2_Фроловское_из_ОЭС_Юга+ПШ","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoFrolPSH);
//        ArrayList<String> tableSever = new ArrayList<>(ParseExcelTable.parseExcelTable("data/Sever.xlsx"));
//        CreateExcelTable.table(tableSever);
//        ArrayList<String> tableShachti = new ArrayList<>(ParseExcelTable.parseExcelTable("data/Shachti.xlsx"));
//        CreateExcelTable.table(tableShachti);
//        ArrayList<String> tableVolRostBL12 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/VolRost_BL1_BL2.xlsx"));
//        CreateExcelTable.table(tableVolRostBL12);
//        HashSet<String> volRost12BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1_BL2.xlsx", 0));
//        HashSet<String> volRost12BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1_BL2.xlsx", 1));
//        HashSet<String> volRost12BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1_BL2.xlsx", 2));
//        HashSet<String> volRost12BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1_BL2.xlsx", 3));
//        HashSet<String> volRost12BL5 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1_BL2.xlsx", 4));
//        HashSet<String> volRost12BL6 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1_BL2.xlsx", 5));
//        HashSet<String> volRost12BL7 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1_BL2.xlsx", 6));
//        ArrayList<String> listFpoVolRostBl12 =new ArrayList<>();
//        listFpoVolRostBl12.addAll(ParseExcelTableFpo.createTableFpoString(volRost12BL2,volRost12BL1,"{ВР_БЛ12}","КПР-1_Волгоград-Ростов+Бл-1+Бл-2","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl12.addAll(ParseExcelTableFpo.createTableFpoString(volRost12BL3,volRost12BL1,"{ВР_БЛ12}","КПР-1_Волгоград-Ростов+Бл-1+Бл-2","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl12.addAll(ParseExcelTableFpo.createTableFpoString(volRost12BL1,volRost12BL2,"{ВР_БЛ12}","КПР-3_Волгоград-Ростов+Бл-1+Бл-2","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl12.addAll(ParseExcelTableFpo.createTableFpoString(volRost12BL3,volRost12BL2,"{ВР_БЛ12}","КПР-3_Волгоград-Ростов+Бл-1+Бл-2","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl12.addAll(ParseExcelTableFpo.createTableFpoString(volRost12BL1,volRost12BL3,"{ВР_БЛ12}","КПР-2_Волгоград-Ростов+Бл-1+Бл-2","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl12.addAll(ParseExcelTableFpo.createTableFpoString(volRost12BL2,volRost12BL3,"{ВР_БЛ12}","КПР-2_Волгоград-Ростов+Бл-1+Бл-2","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl12.addAll(ParseExcelTableFpo.createTableFpoString(volRost12BL5,volRost12BL4,"{ВР_БЛ12}","КПР-4_Волгоград-Ростов+Бл-1+Бл-2","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl12.addAll(ParseExcelTableFpo.createTableFpoString(volRost12BL6,volRost12BL4,"{ВР_БЛ12}","КПР-4_Волгоград-Ростов+Бл-1+Бл-2","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl12.addAll(ParseExcelTableFpo.createTableFpoString(volRost12BL7,volRost12BL4,"{ВР_БЛ12}","КПР-4_Волгоград-Ростов+Бл-1+Бл-2","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl12.addAll(ParseExcelTableFpo.createTableFpoString(volRost12BL4,volRost12BL5,"{ВР_БЛ12}","КПР-2_Волгоград-Ростов+Бл-1+Бл-2","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl12.addAll(ParseExcelTableFpo.createTableFpoString(volRost12BL6,volRost12BL5,"{ВР_БЛ12}","КПР-2_Волгоград-Ростов+Бл-1+Бл-2","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl12.addAll(ParseExcelTableFpo.createTableFpoString(volRost12BL7,volRost12BL5,"{ВР_БЛ12}","КПР-2_Волгоград-Ростов+Бл-1+Бл-2","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl12.addAll(ParseExcelTableFpo.createTableFpoString(volRost12BL4,volRost12BL6,"{ВР_БЛ12}","КПР-1_Волгоград-Ростов+Бл-1+Бл-2","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl12.addAll(ParseExcelTableFpo.createTableFpoString(volRost12BL5,volRost12BL6,"{ВР_БЛ12}","КПР-1_Волгоград-Ростов+Бл-1+Бл-2","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl12.addAll(ParseExcelTableFpo.createTableFpoString(volRost12BL7,volRost12BL6,"{ВР_БЛ12}","КПР-1_Волгоград-Ростов+Бл-1+Бл-2","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl12.addAll(ParseExcelTableFpo.createTableFpoString(volRost12BL4,volRost12BL7,"{ВР_БЛ12}","КПР-3_Волгоград-Ростов+Бл-1+Бл-2","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl12.addAll(ParseExcelTableFpo.createTableFpoString(volRost12BL5,volRost12BL7,"{ВР_БЛ12}","КПР-3_Волгоград-Ростов+Бл-1+Бл-2","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl12.addAll(ParseExcelTableFpo.createTableFpoString(volRost12BL6,volRost12BL7,"{ВР_БЛ12}","КПР-3_Волгоград-Ростов+Бл-1+Бл-2","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoVolRostBl12);
//        ArrayList<String> tableVolRostBL13 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/VolRost_BL1_BL3.xlsx"));
//        CreateExcelTable.table(tableVolRostBL13);
//        HashSet<String> volRost13BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1_BL3.xlsx", 0));
//        HashSet<String> volRost13BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1_BL3.xlsx", 1));
//        HashSet<String> volRost13BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1_BL3.xlsx", 2));
//        HashSet<String> volRost13BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1_BL3.xlsx", 3));
//        HashSet<String> volRost13BL5 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1_BL3.xlsx", 4));
//        HashSet<String> volRost13BL6 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1_BL3.xlsx", 5));
//        HashSet<String> volRost13BL7 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1_BL3.xlsx", 6));
//        ArrayList<String> listFpoVolRostBl13 =new ArrayList<>();
//        listFpoVolRostBl13.addAll(ParseExcelTableFpo.createTableFpoString(volRost13BL2,volRost13BL1,"{ВР_БЛ13}","КПР-1_Волгоград-Ростов+Бл-1+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl13.addAll(ParseExcelTableFpo.createTableFpoString(volRost13BL3,volRost13BL1,"{ВР_БЛ13}","КПР-1_Волгоград-Ростов+Бл-1+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl13.addAll(ParseExcelTableFpo.createTableFpoString(volRost13BL1,volRost13BL2,"{ВР_БЛ13}","КПР-3_Волгоград-Ростов+Бл-1+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl13.addAll(ParseExcelTableFpo.createTableFpoString(volRost13BL3,volRost13BL2,"{ВР_БЛ13}","КПР-3_Волгоград-Ростов+Бл-1+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl13.addAll(ParseExcelTableFpo.createTableFpoString(volRost13BL1,volRost13BL3,"{ВР_БЛ13}","КПР-2_Волгоград-Ростов+Бл-1+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl13.addAll(ParseExcelTableFpo.createTableFpoString(volRost13BL2,volRost13BL3,"{ВР_БЛ13}","КПР-2_Волгоград-Ростов+Бл-1+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl13.addAll(ParseExcelTableFpo.createTableFpoString(volRost13BL5,volRost13BL4,"{ВР_БЛ13}","КПР-4_Волгоград-Ростов+Бл-1+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl13.addAll(ParseExcelTableFpo.createTableFpoString(volRost13BL6,volRost13BL4,"{ВР_БЛ13}","КПР-4_Волгоград-Ростов+Бл-1+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl13.addAll(ParseExcelTableFpo.createTableFpoString(volRost13BL7,volRost13BL4,"{ВР_БЛ13}","КПР-4_Волгоград-Ростов+Бл-1+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl13.addAll(ParseExcelTableFpo.createTableFpoString(volRost13BL4,volRost13BL5,"{ВР_БЛ13}","КПР-2_Волгоград-Ростов+Бл-1+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl13.addAll(ParseExcelTableFpo.createTableFpoString(volRost13BL6,volRost13BL5,"{ВР_БЛ13}","КПР-2_Волгоград-Ростов+Бл-1+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl13.addAll(ParseExcelTableFpo.createTableFpoString(volRost13BL7,volRost13BL5,"{ВР_БЛ13}","КПР-2_Волгоград-Ростов+Бл-1+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl13.addAll(ParseExcelTableFpo.createTableFpoString(volRost13BL4,volRost13BL6,"{ВР_БЛ13}","КПР-1_Волгоград-Ростов+Бл-1+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl13.addAll(ParseExcelTableFpo.createTableFpoString(volRost13BL5,volRost13BL6,"{ВР_БЛ13}","КПР-1_Волгоград-Ростов+Бл-1+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl13.addAll(ParseExcelTableFpo.createTableFpoString(volRost13BL7,volRost13BL6,"{ВР_БЛ13}","КПР-1_Волгоград-Ростов+Бл-1+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl13.addAll(ParseExcelTableFpo.createTableFpoString(volRost13BL4,volRost13BL7,"{ВР_БЛ13}","КПР-3_Волгоград-Ростов+Бл-1+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl13.addAll(ParseExcelTableFpo.createTableFpoString(volRost13BL5,volRost13BL7,"{ВР_БЛ13}","КПР-3_Волгоград-Ростов+Бл-1+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl13.addAll(ParseExcelTableFpo.createTableFpoString(volRost13BL6,volRost13BL7,"{ВР_БЛ13}","КПР-3_Волгоград-Ростов+Бл-1+Бл-3","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoVolRostBl13);
//        ArrayList<String> tableVolRostBL23 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/VolRost_BL2_BL3.xlsx"));
//        CreateExcelTable.table(tableVolRostBL23);
//        HashSet<String> volRost23BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL2_BL3.xlsx", 0));
//        HashSet<String> volRost23BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL2_BL3.xlsx", 1));
//        HashSet<String> volRost23BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL2_BL3.xlsx", 2));
//        HashSet<String> volRost23BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL2_BL3.xlsx", 3));
//        HashSet<String> volRost23BL5 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL2_BL3.xlsx", 4));
//        HashSet<String> volRost23BL6 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL2_BL3.xlsx", 5));
//        HashSet<String> volRost23BL7 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL2_BL3.xlsx", 6));
//        ArrayList<String> listFpoVolRostBl23 =new ArrayList<>();
//        listFpoVolRostBl23.addAll(ParseExcelTableFpo.createTableFpoString(volRost23BL2,volRost23BL1,"{ВР_БЛ23}","КПР-1_Волгоград-Ростов+Бл-2+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl23.addAll(ParseExcelTableFpo.createTableFpoString(volRost23BL3,volRost23BL1,"{ВР_БЛ23}","КПР-1_Волгоград-Ростов+Бл-2+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl23.addAll(ParseExcelTableFpo.createTableFpoString(volRost23BL1,volRost23BL2,"{ВР_БЛ23}","КПР-3_Волгоград-Ростов+Бл-2+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl23.addAll(ParseExcelTableFpo.createTableFpoString(volRost23BL3,volRost23BL2,"{ВР_БЛ23}","КПР-3_Волгоград-Ростов+Бл-2+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl23.addAll(ParseExcelTableFpo.createTableFpoString(volRost23BL1,volRost23BL3,"{ВР_БЛ23}","КПР-2_Волгоград-Ростов+Бл-2+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl23.addAll(ParseExcelTableFpo.createTableFpoString(volRost23BL2,volRost23BL3,"{ВР_БЛ23}","КПР-2_Волгоград-Ростов+Бл-2+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl23.addAll(ParseExcelTableFpo.createTableFpoString(volRost23BL5,volRost23BL4,"{ВР_БЛ23}","КПР-4_Волгоград-Ростов+Бл-2+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl23.addAll(ParseExcelTableFpo.createTableFpoString(volRost23BL6,volRost23BL4,"{ВР_БЛ23}","КПР-4_Волгоград-Ростов+Бл-2+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl23.addAll(ParseExcelTableFpo.createTableFpoString(volRost23BL7,volRost23BL4,"{ВР_БЛ23}","КПР-4_Волгоград-Ростов+Бл-2+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl23.addAll(ParseExcelTableFpo.createTableFpoString(volRost23BL4,volRost23BL5,"{ВР_БЛ23}","КПР-2_Волгоград-Ростов+Бл-2+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl23.addAll(ParseExcelTableFpo.createTableFpoString(volRost23BL6,volRost23BL5,"{ВР_БЛ23}","КПР-2_Волгоград-Ростов+Бл-2+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl23.addAll(ParseExcelTableFpo.createTableFpoString(volRost23BL7,volRost23BL5,"{ВР_БЛ23}","КПР-2_Волгоград-Ростов+Бл-2+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl23.addAll(ParseExcelTableFpo.createTableFpoString(volRost23BL4,volRost23BL6,"{ВР_БЛ23}","КПР-1_Волгоград-Ростов+Бл-2+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl23.addAll(ParseExcelTableFpo.createTableFpoString(volRost23BL5,volRost23BL6,"{ВР_БЛ23}","КПР-1_Волгоград-Ростов+Бл-2+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl23.addAll(ParseExcelTableFpo.createTableFpoString(volRost23BL7,volRost23BL6,"{ВР_БЛ23}","КПР-1_Волгоград-Ростов+Бл-2+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl23.addAll(ParseExcelTableFpo.createTableFpoString(volRost23BL4,volRost23BL7,"{ВР_БЛ23}","КПР-3_Волгоград-Ростов+Бл-2+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl23.addAll(ParseExcelTableFpo.createTableFpoString(volRost23BL5,volRost23BL7,"{ВР_БЛ23}","КПР-3_Волгоград-Ростов+Бл-2+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl23.addAll(ParseExcelTableFpo.createTableFpoString(volRost23BL6,volRost23BL7,"{ВР_БЛ23}","КПР-3_Волгоград-Ростов+Бл-2+Бл-3","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoVolRostBl23);
//        ArrayList<String> tableVolRostBL14 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/VolRost_BL1_BL4.xlsx"));
//        CreateExcelTable.table(tableVolRostBL14);
//        HashSet<String> volRost14BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1_BL4.xlsx", 0));
//        HashSet<String> volRost14BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1_BL4.xlsx", 1));
//        HashSet<String> volRost14BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1_BL4.xlsx", 2));
//        HashSet<String> volRost14BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1_BL4.xlsx", 3));
//        HashSet<String> volRost14BL5 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1_BL4.xlsx", 4));
//        HashSet<String> volRost14BL6 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1_BL4.xlsx", 5));
//        HashSet<String> volRost14BL7 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL1_BL4.xlsx", 6));
//        ArrayList<String> listFpoVolRostBl14 =new ArrayList<>();
//        listFpoVolRostBl14.addAll(ParseExcelTableFpo.createTableFpoString(volRost14BL2,volRost14BL1,"{ВР_БЛ14}","КПР-1_Волгоград-Ростов+Бл-1+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl14.addAll(ParseExcelTableFpo.createTableFpoString(volRost14BL3,volRost14BL1,"{ВР_БЛ14}","КПР-1_Волгоград-Ростов+Бл-1+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl14.addAll(ParseExcelTableFpo.createTableFpoString(volRost14BL1,volRost14BL2,"{ВР_БЛ14}","КПР-3_Волгоград-Ростов+Бл-1+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl14.addAll(ParseExcelTableFpo.createTableFpoString(volRost14BL3,volRost14BL2,"{ВР_БЛ14}","КПР-3_Волгоград-Ростов+Бл-1+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl14.addAll(ParseExcelTableFpo.createTableFpoString(volRost14BL1,volRost14BL3,"{ВР_БЛ14}","КПР-2_Волгоград-Ростов+Бл-1+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl14.addAll(ParseExcelTableFpo.createTableFpoString(volRost14BL2,volRost14BL3,"{ВР_БЛ14}","КПР-2_Волгоград-Ростов+Бл-1+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl14.addAll(ParseExcelTableFpo.createTableFpoString(volRost14BL5,volRost14BL4,"{ВР_БЛ14}","КПР-4_Волгоград-Ростов+Бл-1+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl14.addAll(ParseExcelTableFpo.createTableFpoString(volRost14BL6,volRost14BL4,"{ВР_БЛ14}","КПР-4_Волгоград-Ростов+Бл-1+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl14.addAll(ParseExcelTableFpo.createTableFpoString(volRost14BL7,volRost14BL4,"{ВР_БЛ14}","КПР-4_Волгоград-Ростов+Бл-1+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl14.addAll(ParseExcelTableFpo.createTableFpoString(volRost14BL4,volRost14BL5,"{ВР_БЛ14}","КПР-2_Волгоград-Ростов+Бл-1+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl14.addAll(ParseExcelTableFpo.createTableFpoString(volRost14BL6,volRost14BL5,"{ВР_БЛ14}","КПР-2_Волгоград-Ростов+Бл-1+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl14.addAll(ParseExcelTableFpo.createTableFpoString(volRost14BL7,volRost14BL5,"{ВР_БЛ14}","КПР-2_Волгоград-Ростов+Бл-1+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl14.addAll(ParseExcelTableFpo.createTableFpoString(volRost14BL4,volRost14BL6,"{ВР_БЛ14}","КПР-1_Волгоград-Ростов+Бл-1+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl14.addAll(ParseExcelTableFpo.createTableFpoString(volRost14BL5,volRost14BL6,"{ВР_БЛ14}","КПР-1_Волгоград-Ростов+Бл-1+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl14.addAll(ParseExcelTableFpo.createTableFpoString(volRost14BL7,volRost14BL6,"{ВР_БЛ14}","КПР-1_Волгоград-Ростов+Бл-1+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl14.addAll(ParseExcelTableFpo.createTableFpoString(volRost14BL4,volRost14BL7,"{ВР_БЛ14}","КПР-3_Волгоград-Ростов+Бл-1+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl14.addAll(ParseExcelTableFpo.createTableFpoString(volRost14BL5,volRost14BL7,"{ВР_БЛ14}","КПР-3_Волгоград-Ростов+Бл-1+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl14.addAll(ParseExcelTableFpo.createTableFpoString(volRost14BL6,volRost14BL7,"{ВР_БЛ14}","КПР-3_Волгоград-Ростов+Бл-1+Бл-4","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoVolRostBl14);
//        ArrayList<String> tableVolRostBL24 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/VolRost_BL2_BL4.xlsx"));
//        CreateExcelTable.table(tableVolRostBL24);
//        HashSet<String> volRost24BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL2_BL4.xlsx", 0));
//        HashSet<String> volRost24BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL2_BL4.xlsx", 1));
//        HashSet<String> volRost24BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL2_BL4.xlsx", 2));
//        HashSet<String> volRost24BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL2_BL4.xlsx", 3));
//        HashSet<String> volRost24BL5 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL2_BL4.xlsx", 4));
//        HashSet<String> volRost24BL6 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL2_BL4.xlsx", 5));
//        HashSet<String> volRost24BL7 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL2_BL4.xlsx", 6));
//        ArrayList<String> listFpoVolRostBl24 =new ArrayList<>();
//        listFpoVolRostBl24.addAll(ParseExcelTableFpo.createTableFpoString(volRost24BL2,volRost24BL1,"{ВР_БЛ24}","КПР-1_Волгоград-Ростов+Бл-2+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl24.addAll(ParseExcelTableFpo.createTableFpoString(volRost24BL3,volRost24BL1,"{ВР_БЛ24}","КПР-1_Волгоград-Ростов+Бл-2+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl24.addAll(ParseExcelTableFpo.createTableFpoString(volRost24BL1,volRost24BL2,"{ВР_БЛ24}","КПР-3_Волгоград-Ростов+Бл-2+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl24.addAll(ParseExcelTableFpo.createTableFpoString(volRost24BL3,volRost24BL2,"{ВР_БЛ24}","КПР-3_Волгоград-Ростов+Бл-2+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl24.addAll(ParseExcelTableFpo.createTableFpoString(volRost24BL1,volRost24BL3,"{ВР_БЛ24}","КПР-2_Волгоград-Ростов+Бл-2+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl24.addAll(ParseExcelTableFpo.createTableFpoString(volRost24BL2,volRost24BL3,"{ВР_БЛ24}","КПР-2_Волгоград-Ростов+Бл-2+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl24.addAll(ParseExcelTableFpo.createTableFpoString(volRost24BL5,volRost24BL4,"{ВР_БЛ24}","КПР-4_Волгоград-Ростов+Бл-2+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl24.addAll(ParseExcelTableFpo.createTableFpoString(volRost24BL6,volRost24BL4,"{ВР_БЛ24}","КПР-4_Волгоград-Ростов+Бл-2+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl24.addAll(ParseExcelTableFpo.createTableFpoString(volRost24BL7,volRost24BL4,"{ВР_БЛ24}","КПР-4_Волгоград-Ростов+Бл-2+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl24.addAll(ParseExcelTableFpo.createTableFpoString(volRost24BL4,volRost24BL5,"{ВР_БЛ24}","КПР-2_Волгоград-Ростов+Бл-2+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl24.addAll(ParseExcelTableFpo.createTableFpoString(volRost24BL6,volRost24BL5,"{ВР_БЛ24}","КПР-2_Волгоград-Ростов+Бл-2+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl24.addAll(ParseExcelTableFpo.createTableFpoString(volRost24BL7,volRost24BL5,"{ВР_БЛ24}","КПР-2_Волгоград-Ростов+Бл-2+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl24.addAll(ParseExcelTableFpo.createTableFpoString(volRost24BL4,volRost24BL6,"{ВР_БЛ24}","КПР-1_Волгоград-Ростов+Бл-2+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl24.addAll(ParseExcelTableFpo.createTableFpoString(volRost24BL5,volRost24BL6,"{ВР_БЛ24}","КПР-1_Волгоград-Ростов+Бл-2+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl24.addAll(ParseExcelTableFpo.createTableFpoString(volRost24BL7,volRost24BL6,"{ВР_БЛ24}","КПР-1_Волгоград-Ростов+Бл-2+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl24.addAll(ParseExcelTableFpo.createTableFpoString(volRost24BL4,volRost24BL7,"{ВР_БЛ24}","КПР-3_Волгоград-Ростов+Бл-2+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl24.addAll(ParseExcelTableFpo.createTableFpoString(volRost24BL5,volRost24BL7,"{ВР_БЛ24}","КПР-3_Волгоград-Ростов+Бл-2+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl24.addAll(ParseExcelTableFpo.createTableFpoString(volRost24BL6,volRost24BL7,"{ВР_БЛ24}","КПР-3_Волгоград-Ростов+Бл-2+Бл-4","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoVolRostBl24);
//        ArrayList<String> tableVolRostBL34 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/VolRost_BL3_BL4.xlsx"));
//        CreateExcelTable.table(tableVolRostBL34);
//        HashSet<String> volRost34BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL3_BL4.xlsx", 0));
//        HashSet<String> volRost34BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL3_BL4.xlsx", 1));
//        HashSet<String> volRost34BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL3_BL4.xlsx", 2));
//        HashSet<String> volRost34BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL3_BL4.xlsx", 3));
//        HashSet<String> volRost34BL5 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL3_BL4.xlsx", 4));
//        HashSet<String> volRost34BL6 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL3_BL4.xlsx", 5));
//        HashSet<String> volRost34BL7 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/VolRost_BL3_BL4.xlsx", 6));
//        ArrayList<String> listFpoVolRostBl34 =new ArrayList<>();
//        listFpoVolRostBl34.addAll(ParseExcelTableFpo.createTableFpoString(volRost34BL2,volRost34BL1,"{ВР_БЛ34}","КПР-1_Волгоград-Ростов+Бл-3+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl34.addAll(ParseExcelTableFpo.createTableFpoString(volRost34BL3,volRost34BL1,"{ВР_БЛ34}","КПР-1_Волгоград-Ростов+Бл-3+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl34.addAll(ParseExcelTableFpo.createTableFpoString(volRost34BL1,volRost34BL2,"{ВР_БЛ34}","КПР-3_Волгоград-Ростов+Бл-3+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl34.addAll(ParseExcelTableFpo.createTableFpoString(volRost34BL3,volRost34BL2,"{ВР_БЛ34}","КПР-3_Волгоград-Ростов+Бл-3+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl34.addAll(ParseExcelTableFpo.createTableFpoString(volRost34BL1,volRost34BL3,"{ВР_БЛ34}","КПР-2_Волгоград-Ростов+Бл-3+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl34.addAll(ParseExcelTableFpo.createTableFpoString(volRost34BL2,volRost34BL3,"{ВР_БЛ34}","КПР-2_Волгоград-Ростов+Бл-3+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolRostBl34.addAll(ParseExcelTableFpo.createTableFpoString(volRost34BL5,volRost34BL4,"{ВР_БЛ34}","КПР-4_Волгоград-Ростов+Бл-3+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl34.addAll(ParseExcelTableFpo.createTableFpoString(volRost34BL6,volRost34BL4,"{ВР_БЛ34}","КПР-4_Волгоград-Ростов+Бл-3+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl34.addAll(ParseExcelTableFpo.createTableFpoString(volRost34BL7,volRost34BL4,"{ВР_БЛ34}","КПР-4_Волгоград-Ростов+Бл-3+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl34.addAll(ParseExcelTableFpo.createTableFpoString(volRost34BL4,volRost34BL5,"{ВР_БЛ34}","КПР-2_Волгоград-Ростов+Бл-3+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl34.addAll(ParseExcelTableFpo.createTableFpoString(volRost34BL6,volRost34BL5,"{ВР_БЛ34}","КПР-2_Волгоград-Ростов+Бл-3+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl34.addAll(ParseExcelTableFpo.createTableFpoString(volRost34BL7,volRost34BL5,"{ВР_БЛ34}","КПР-2_Волгоград-Ростов+Бл-3+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl34.addAll(ParseExcelTableFpo.createTableFpoString(volRost34BL4,volRost34BL6,"{ВР_БЛ34}","КПР-1_Волгоград-Ростов+Бл-3+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl34.addAll(ParseExcelTableFpo.createTableFpoString(volRost34BL5,volRost34BL6,"{ВР_БЛ34}","КПР-1_Волгоград-Ростов+Бл-3+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl34.addAll(ParseExcelTableFpo.createTableFpoString(volRost34BL7,volRost34BL6,"{ВР_БЛ34}","КПР-1_Волгоград-Ростов+Бл-3+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl34.addAll(ParseExcelTableFpo.createTableFpoString(volRost34BL4,volRost34BL7,"{ВР_БЛ34}","КПР-3_Волгоград-Ростов+Бл-3+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl34.addAll(ParseExcelTableFpo.createTableFpoString(volRost34BL5,volRost34BL7,"{ВР_БЛ34}","КПР-3_Волгоград-Ростов+Бл-3+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolRostBl34.addAll(ParseExcelTableFpo.createTableFpoString(volRost34BL6,volRost34BL7,"{ВР_БЛ34}","КПР-3_Волгоград-Ростов+Бл-3+Бл-4","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoVolRostBl34);
//        ArrayList<String> tableVolBL12 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/Vol_BL1_BL2.xlsx"));
//        CreateExcelTable.table(tableVolBL12);
//        HashSet<String> vol12BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL1_BL2.xlsx", 0));
//        HashSet<String> vol12BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL1_BL2.xlsx", 1));
//        HashSet<String> vol12BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL1_BL2.xlsx", 2));
//        HashSet<String> vol12BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL1_BL2.xlsx", 3));
//        ArrayList<String> listFpoVolBL12 =new ArrayList<>();
//        listFpoVolBL12.addAll(ParseExcelTableFpo.createTableFpoString(vol12BL2,vol12BL1,"{В_БЛ12}","КПР-1_Волгоградское+Бл-1+Бл-2","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolBL12.addAll(ParseExcelTableFpo.createTableFpoString(vol12BL1,vol12BL2,"{В_БЛ12}","КПР-2_Волгоградское+Бл-1+Бл-2","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolBL12.addAll(ParseExcelTableFpo.createTableFpoString(vol12BL4,vol12BL3,"{В_БЛ12}","КПР-1_Волгоградское+Бл-1+Бл-2","[Текущий_сезон=ЗИМА]"));
//        listFpoVolBL12.addAll(ParseExcelTableFpo.createTableFpoString(vol12BL3,vol12BL4,"{В_БЛ12}","КПР-2_Волгоградское+Бл-1+Бл-2","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoVolBL12);
//        ArrayList<String> tableVolBL13 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/Vol_BL1_BL3.xlsx"));
//        CreateExcelTable.table(tableVolBL13);
//        HashSet<String> vol13BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL1_BL3.xlsx", 0));
//        HashSet<String> vol13BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL1_BL3.xlsx", 1));
//        HashSet<String> vol13BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL1_BL3.xlsx", 2));
//        HashSet<String> vol13BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL1_BL3.xlsx", 3));
//        ArrayList<String> listFpoVolBL13 =new ArrayList<>();
//        listFpoVolBL13.addAll(ParseExcelTableFpo.createTableFpoString(vol13BL2,vol13BL1,"{В_БЛ13}","КПР-1_Волгоградское+Бл-1+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolBL13.addAll(ParseExcelTableFpo.createTableFpoString(vol13BL1,vol13BL2,"{В_БЛ13}","КПР-2_Волгоградское+Бл-1+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolBL13.addAll(ParseExcelTableFpo.createTableFpoString(vol13BL4,vol13BL3,"{В_БЛ13}","КПР-1_Волгоградское+Бл-1+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVolBL13.addAll(ParseExcelTableFpo.createTableFpoString(vol13BL3,vol13BL4,"{В_БЛ13}","КПР-2_Волгоградское+Бл-1+Бл-3","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoVolBL13);
//        ArrayList<String> tableVolBL23 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/Vol_BL2_BL3.xlsx"));
//        CreateExcelTable.table(tableVolBL23);
//        HashSet<String> vol23BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL2_BL3.xlsx", 0));
//        HashSet<String> vol23BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL2_BL3.xlsx", 1));
//        HashSet<String> vol23BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL2_BL3.xlsx", 2));
//        HashSet<String> vol23BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL2_BL3.xlsx", 3));
//        ArrayList<String> listFpoVolBL23 =new ArrayList<>();
//        listFpoVolBL23.addAll(ParseExcelTableFpo.createTableFpoString(vol23BL2,vol23BL1,"{В_БЛ23}","КПР-1_Волгоградское+Бл-2+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolBL23.addAll(ParseExcelTableFpo.createTableFpoString(vol23BL1,vol23BL2,"{В_БЛ23}","КПР-2_Волгоградское+Бл-2+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolBL23.addAll(ParseExcelTableFpo.createTableFpoString(vol23BL4,vol23BL3,"{В_БЛ23}","КПР-1_Волгоградское+Бл-2+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoVolBL23.addAll(ParseExcelTableFpo.createTableFpoString(vol23BL3,vol23BL4,"{В_БЛ23}","КПР-2_Волгоградское+Бл-2+Бл-3","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoVolBL23);
//        ArrayList<String> tableVolBL14 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/Vol_BL1_BL4.xlsx"));
//        CreateExcelTable.table(tableVolBL14);
//        HashSet<String> vol14BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL1_BL4.xlsx", 0));
//        HashSet<String> vol14BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL1_BL4.xlsx", 1));
//        HashSet<String> vol14BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL1_BL4.xlsx", 2));
//        HashSet<String> vol14BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL1_BL4.xlsx", 3));
//        ArrayList<String> listFpoVolBL14 =new ArrayList<>();
//        listFpoVolBL14.addAll(ParseExcelTableFpo.createTableFpoString(vol14BL2,vol14BL1,"{В_БЛ14}","КПР-1_Волгоградское+Бл-1+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolBL14.addAll(ParseExcelTableFpo.createTableFpoString(vol14BL1,vol14BL2,"{В_БЛ14}","КПР-2_Волгоградское+Бл-1+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolBL14.addAll(ParseExcelTableFpo.createTableFpoString(vol14BL4,vol14BL3,"{В_БЛ14}","КПР-1_Волгоградское+Бл-1+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolBL14.addAll(ParseExcelTableFpo.createTableFpoString(vol14BL3,vol14BL4,"{В_БЛ14}","КПР-2_Волгоградское+Бл-1+Бл-4","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoVolBL14);
//        ArrayList<String> tableVolBL24 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/Vol_BL2_BL4.xlsx"));
//        CreateExcelTable.table(tableVolBL24);
//        HashSet<String> vol24BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL2_BL4.xlsx", 0));
//        HashSet<String> vol24BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL2_BL4.xlsx", 1));
//        HashSet<String> vol24BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL2_BL4.xlsx", 2));
//        HashSet<String> vol24BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL2_BL4.xlsx", 3));
//        ArrayList<String> listFpoVolBL24 =new ArrayList<>();
//        listFpoVolBL24.addAll(ParseExcelTableFpo.createTableFpoString(vol24BL2,vol24BL1,"{В_БЛ24}","КПР-1_Волгоградское+Бл-2+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolBL24.addAll(ParseExcelTableFpo.createTableFpoString(vol24BL1,vol24BL2,"{В_БЛ24}","КПР-2_Волгоградское+Бл-2+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolBL24.addAll(ParseExcelTableFpo.createTableFpoString(vol24BL4,vol24BL3,"{В_БЛ24}","КПР-1_Волгоградское+Бл-2+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolBL24.addAll(ParseExcelTableFpo.createTableFpoString(vol24BL3,vol24BL4,"{В_БЛ24}","КПР-2_Волгоградское+Бл-2+Бл-4","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoVolBL24);
//        ArrayList<String> tableVolBL34 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/Vol_BL3_BL4.xlsx"));
//        CreateExcelTable.table(tableVolBL34);
//        HashSet<String> vol34BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL3_BL4.xlsx", 0));
//        HashSet<String> vol34BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL3_BL4.xlsx", 1));
//        HashSet<String> vol34BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL3_BL4.xlsx", 2));
//        HashSet<String> vol34BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Vol_BL3_BL4.xlsx", 3));
//        ArrayList<String> listFpoVolBL34 =new ArrayList<>();
//        listFpoVolBL34.addAll(ParseExcelTableFpo.createTableFpoString(vol34BL2,vol34BL1,"{В_БЛ34}","КПР-1_Волгоградское+Бл-3+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolBL34.addAll(ParseExcelTableFpo.createTableFpoString(vol34BL1,vol34BL2,"{В_БЛ34}","КПР-2_Волгоградское+Бл-3+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoVolBL34.addAll(ParseExcelTableFpo.createTableFpoString(vol34BL4,vol34BL3,"{В_БЛ34}","КПР-1_Волгоградское+Бл-3+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoVolBL34.addAll(ParseExcelTableFpo.createTableFpoString(vol34BL3,vol34BL4,"{В_БЛ34}","КПР-2_Волгоградское+Бл-3+Бл-4","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoVolBL34);
//        ArrayList<String> tableFrolBL12 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/Frol_BL1_BL2.xlsx"));
//        CreateExcelTable.table(tableFrolBL12);
//        HashSet<String> frol12BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL1_BL2.xlsx", 0));
//        HashSet<String> frol12BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL1_BL2.xlsx", 1));
//        HashSet<String> frol12BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL1_BL2.xlsx", 2));
//        HashSet<String> frol12BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL1_BL2.xlsx", 3));
//        ArrayList<String> listFpoFrolBL12 =new ArrayList<>();
//        listFpoFrolBL12.addAll(ParseExcelTableFpo.createTableFpoString(frol12BL2,frol12BL1,"{Ф_БЛ12}","КПР-1_Фроловское+Бл-1+Бл-2","[Текущий_сезон=ЛЕТО]"));
//        listFpoFrolBL12.addAll(ParseExcelTableFpo.createTableFpoString(frol12BL1,frol12BL2,"{Ф_БЛ12}","КПР-2_Фроловское+Бл-1+Бл-2","[Текущий_сезон=ЛЕТО]"));
//        listFpoFrolBL12.addAll(ParseExcelTableFpo.createTableFpoString(frol12BL4,frol12BL3,"{Ф_БЛ12}","КПР-1_Фроловское+Бл-1+Бл-2","[Текущий_сезон=ЗИМА]"));
//        listFpoFrolBL12.addAll(ParseExcelTableFpo.createTableFpoString(frol12BL3,frol12BL4,"{Ф_БЛ12}","КПР-2_Фроловское+Бл-1+Бл-2","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoFrolBL12);
//        ArrayList<String> tableFrolBL13 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/Frol_BL1_BL3.xlsx"));
//        CreateExcelTable.table(tableFrolBL13);
//        HashSet<String> frol13BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL1_BL3.xlsx", 0));
//        HashSet<String> frol13BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL1_BL3.xlsx", 1));
//        HashSet<String> frol13BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL1_BL3.xlsx", 2));
//        HashSet<String> frol13BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL1_BL3.xlsx", 3));
//        ArrayList<String> listFpoFrolBL13 =new ArrayList<>();
//        listFpoFrolBL13.addAll(ParseExcelTableFpo.createTableFpoString(frol13BL2,frol13BL1,"{Ф_БЛ13}","КПР-1_Фроловское+Бл-1+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoFrolBL13.addAll(ParseExcelTableFpo.createTableFpoString(frol13BL1,frol13BL2,"{Ф_БЛ13}","КПР-2_Фроловское+Бл-1+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoFrolBL13.addAll(ParseExcelTableFpo.createTableFpoString(frol13BL4,frol13BL3,"{Ф_БЛ13}","КПР-1_Фроловское+Бл-1+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoFrolBL13.addAll(ParseExcelTableFpo.createTableFpoString(frol13BL3,frol13BL4,"{Ф_БЛ13}","КПР-2_Фроловское+Бл-1+Бл-3","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoFrolBL13);
//        ArrayList<String> tableFrolBL23 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/Frol_BL2_BL3.xlsx"));
//        CreateExcelTable.table(tableFrolBL23);
//        HashSet<String> frol23BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL2_BL3.xlsx", 0));
//        HashSet<String> frol23BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL2_BL3.xlsx", 1));
//        HashSet<String> frol23BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL2_BL3.xlsx", 2));
//        HashSet<String> frol23BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL2_BL3.xlsx", 3));
//        ArrayList<String> listFpoFrolBL23 =new ArrayList<>();
//        listFpoFrolBL23.addAll(ParseExcelTableFpo.createTableFpoString(frol23BL2,frol23BL1,"{Ф_БЛ23}","КПР-1_Фроловское+Бл-2+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoFrolBL23.addAll(ParseExcelTableFpo.createTableFpoString(frol23BL1,frol23BL2,"{Ф_БЛ23}","КПР-2_Фроловское+Бл-2+Бл-3","[Текущий_сезон=ЛЕТО]"));
//        listFpoFrolBL23.addAll(ParseExcelTableFpo.createTableFpoString(frol23BL4,frol23BL3,"{Ф_БЛ23}","КПР-1_Фроловское+Бл-2+Бл-3","[Текущий_сезон=ЗИМА]"));
//        listFpoFrolBL23.addAll(ParseExcelTableFpo.createTableFpoString(frol23BL3,frol23BL4,"{Ф_БЛ23}","КПР-2_Фроловское+Бл-2+Бл-3","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoFrolBL23);
//        ArrayList<String> tableFrolBL14 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/Frol_BL1_BL4.xlsx"));
//        CreateExcelTable.table(tableFrolBL14);
//        HashSet<String> frol14BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL1_BL4.xlsx", 0));
//        HashSet<String> frol14BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL1_BL4.xlsx", 1));
//        HashSet<String> frol14BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL1_BL4.xlsx", 2));
//        HashSet<String> frol14BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL1_BL4.xlsx", 3));
//        ArrayList<String> listFpoFrolBL14 =new ArrayList<>();
//        listFpoFrolBL14.addAll(ParseExcelTableFpo.createTableFpoString(frol14BL2,frol14BL1,"{Ф_БЛ14}","КПР-1_Фроловское+Бл-1+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoFrolBL14.addAll(ParseExcelTableFpo.createTableFpoString(frol14BL1,frol14BL2,"{Ф_БЛ14}","КПР-2_Фроловское+Бл-1+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoFrolBL14.addAll(ParseExcelTableFpo.createTableFpoString(frol14BL4,frol14BL3,"{Ф_БЛ14}","КПР-1_Фроловское+Бл-1+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoFrolBL14.addAll(ParseExcelTableFpo.createTableFpoString(frol14BL3,frol14BL4,"{Ф_БЛ14}","КПР-2_Фроловское+Бл-1+Бл-4","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoFrolBL14);
//        ArrayList<String> tableFrolBL24 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/Frol_BL2_BL4.xlsx"));
//        CreateExcelTable.table(tableFrolBL24);
//        HashSet<String> frol24BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL2_BL4.xlsx", 0));
//        HashSet<String> frol24BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL2_BL4.xlsx", 1));
//        HashSet<String> frol24BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL2_BL4.xlsx", 2));
//        HashSet<String> frol24BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL2_BL4.xlsx", 3));
//        ArrayList<String> listFpoFrolBL24 =new ArrayList<>();
//        listFpoFrolBL24.addAll(ParseExcelTableFpo.createTableFpoString(frol24BL2,frol24BL1,"{Ф_БЛ24}","КПР-1_Фроловское+Бл-2+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoFrolBL24.addAll(ParseExcelTableFpo.createTableFpoString(frol24BL1,frol24BL2,"{Ф_БЛ24}","КПР-2_Фроловское+Бл-2+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoFrolBL24.addAll(ParseExcelTableFpo.createTableFpoString(frol24BL4,frol24BL3,"{Ф_БЛ24}","КПР-1_Фроловское+Бл-2+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoFrolBL24.addAll(ParseExcelTableFpo.createTableFpoString(frol24BL3,frol24BL4,"{Ф_БЛ24}","КПР-2_Фроловское+Бл-2+Бл-4","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoFrolBL24);
//        ArrayList<String> tableFrolBL34 = new ArrayList<>(ParseExcelTable.parseExcelTable("data/Frol_BL3_BL4.xlsx"));
//        CreateExcelTable.table(tableFrolBL34);
//        HashSet<String> frol34BL1 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL3_BL4.xlsx", 0));
//        HashSet<String> frol34BL2 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL3_BL4.xlsx", 1));
//        HashSet<String> frol34BL3 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL3_BL4.xlsx", 2));
//        HashSet<String> frol34BL4 =new HashSet<>(ParseExcelTableFpo.parseExcelTableFpo("data/Frol_BL3_BL4.xlsx", 3));
//        ArrayList<String> listFpoFrolBL34 =new ArrayList<>();
//        listFpoFrolBL34.addAll(ParseExcelTableFpo.createTableFpoString(frol34BL2,frol34BL1,"{Ф_БЛ34}","КПР-1_Фроловское+Бл-3+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoFrolBL34.addAll(ParseExcelTableFpo.createTableFpoString(frol34BL1,frol34BL2,"{Ф_БЛ34}","КПР-2_Фроловское+Бл-3+Бл-4","[Текущий_сезон=ЛЕТО]"));
//        listFpoFrolBL34.addAll(ParseExcelTableFpo.createTableFpoString(frol34BL4,frol34BL3,"{Ф_БЛ34}","КПР-1_Фроловское+Бл-3+Бл-4","[Текущий_сезон=ЗИМА]"));
//        listFpoFrolBL34.addAll(ParseExcelTableFpo.createTableFpoString(frol34BL3,frol34BL4,"{Ф_БЛ34}","КПР-2_Фроловское+Бл-3+Бл-4","[Текущий_сезон=ЗИМА]"));
//        CreateExcelTable.table(listFpoFrolBL34);
        ArrayList<String> listShunt = new ArrayList<>(ParseExcelTableShunt.parseExcelTableShunt());
        CreateExcelTable.table(listShunt);
        CreateExcelTable.closeTable();
    }
}
